runtime: python39
entrypoint: gunicorn -b :$PORT app.app:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  SECRET_KEY: 7a#U?onCvR7.~1r
  API_SECRET: jWY{pXat7'kqa$5
  GOOGLE_APPLICATION_CREDENTIALS: app/credentials/firebase_admin.json